[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
coroutines = "1.10.2"
hilt = "2.57.2"
hiltNavigation = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxSerializationJson = "1.7.3"
ksp = "2.0.21-1.0.25"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
navVersion = "2.9.6"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
mockkVersion = "1.14.6"
room_version = "2.8.4"
okhttpVersion = "4.12.0"
retrofitKotlinxSerialization = "1.0.0"
retrofitVersion = "2.9.0"
testRules = "1.7.0"
turbineVersion = "1.2.1"
appcompat = "1.7.1"
material = "1.13.0"

[libraries]

#Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion"  }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }

#Retrofit
square-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
square-converter-retrofit2 = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion"}
square-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion" }
square-okhttp3-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpVersion" }
square-converter-kotlinxSerialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerialization" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

#Other
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Tests
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
testRules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
mockKotlin = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbineVersion" }

androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }



